apiVersion: v1
kind: Pod
metadata:
  name: utafiti-containers
spec:

  restartPolicy: Always

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

  - name: utafiti-container
    image: utafiti
    volumeMounts:
    - name: shared-data
      mountPath: /app/output
